apiVersion: batch/v1
kind: CronJob
metadata:
  name: travel-planner-langchain-loadgen
  namespace: travel-agent
spec:
  schedule: "*/30 * * * *"  # Every 30 min
  concurrencyPolicy: Forbid  # Prevent overlapping runs
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: travel-planner-langchain-client
            scenario: no-poison
        spec:
          restartPolicy: OnFailure
          containers:
            - name: mcp-client
              image: docker.io/derekmitchell399/travel-planner-loadgen:1.0
              imagePullPolicy: Always
              env:
                # Flask Server URL - using k8s service
                - name: SERVER_URL
                  value: "http://travel-planner-langchain-service.travel-agent.svc.cluster.local:8080"
              command:
                - python
                - client.py
                #- --no-poison
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "100m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                runAsUser: 1000
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: false
