#!/usr/bin/env bash

STATUS_LOG=/run/cloud-init/status.json

if [[ "$#" -ne 2 ]]; then
	echo "Usage: up COUNT REGION"
	exit 1
fi

COMMANDS="jq terraform pssh"

for cmd in $COMMANDS; do
	if ! command -v "$cmd" &> /dev/null; then
		echo "$cmd not found. Please install with your package manager, e.g. brew install $cmd."
		exit 1
	fi
done

COUNT=$1
REGION=$2

while :; do
	terraform apply -var="aws_instance_count=$COUNT" -var="aws_region=$REGION"

	pssh -o sanity-check --par 60 -l ubuntu -A --hosts <(terraform output --json ip|jq -r '.[]') -x "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PreferredAuthentications=password -o PubkeyAuthentication=no" -- "cat ${STATUS_LOG}"

	ERR_COUNT=$(jq ' .v1 | .[] | values | select(.errors? | length > 0) | .errors[] ' sanity-check/* | jq -rs '. | length')

	if [[ $ERR_COUNT -eq 0 ]]; then
		echo "All instances completed cloud-init without errors."
		break;
	else
		echo "Errors found in cloud-init status for some instances."
		jq -r '.v1 | .[] | values | select(.errors? | length > 0) | input_filename' sanity-check/* |
			sed -e 's,sanity-check/,,' |
			{ TF_STATE=$(terraform show --json); while read -r IP; do \
				RNAME=$(jq -r ' .values.root_module.resources[] | select (.values.public_ip == "'"$IP"'") | .address' <<< "$TF_STATE")
				echo "Error found in cloud-init status for instance: $RNAME"
				terraform destroy -var="aws_instance_count=$COUNT" -var="aws_region=$REGION" -target "'$RNAME'"
			done }
	fi
done
