agent:
  config:
    exporters:
      signalfx:
        send_otlp_histograms: true
    processors:
      resource/envname:
        attributes:
        - action: insert
          key: deployment.environment
          value: {{environment}}
    service:
      pipelines:
        traces:
          processors:
          - memory_limiter
          - k8s_attributes
          - batch
          - resourcedetection
          - resource
          - resource/envname
        logs:
          processors:
          - memory_limiter
          - k8s_attributes
          - filter/logs
          - batch
          - resourcedetection
          - resource
          - resource/logs
          - resource/envname
