apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REPLACE_WITH_CLUSTER_CA_DATA
    server: https://REPLACE_WITH_CLUSTER_API_SERVER
  name: clus-ltrobs-2001-event
contexts:
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-01
    user: workshop-students
  name: student-01
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-02
    user: workshop-students
  name: student-02
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-03
    user: workshop-students
  name: student-03
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-04
    user: workshop-students
  name: student-04
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-05
    user: workshop-students
  name: student-05
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-06
    user: workshop-students
  name: student-06
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-07
    user: workshop-students
  name: student-07
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-08
    user: workshop-students
  name: student-08
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-09
    user: workshop-students
  name: student-09
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-10
    user: workshop-students
  name: student-10
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-11
    user: workshop-students
  name: student-11
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-12
    user: workshop-students
  name: student-12
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-13
    user: workshop-students
  name: student-13
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-14
    user: workshop-students
  name: student-14
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-15
    user: workshop-students
  name: student-15
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-16
    user: workshop-students
  name: student-16
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-17
    user: workshop-students
  name: student-17
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-18
    user: workshop-students
  name: student-18
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-19
    user: workshop-students
  name: student-19
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-20
    user: workshop-students
  name: student-20
current-context: student-01
kind: Config
preferences: {}
users:
- name: workshop-students
  user:
    token: REPLACE_WITH_STUDENT_SERVICE_ACCOUNT_TOKEN
