apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: te-demo
  name: thousandeyes
  labels:
    app: thousandeyes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thousandeyes
  template:
    metadata:
      labels:
        app: thousandeyes
    spec:
      hostname: te-agent-aleccham
      containers:
       - name: thousandeyes
         image: 'thousandeyes/enterprise-agent:latest'
         imagePullPolicy: Always
         command:
          - /sbin/my_init
         securityContext:
           capabilities:
             add:
               - NET_ADMIN
               - SYS_ADMIN
         env:
           - name: TEAGENT_ACCOUNT_TOKEN
             valueFrom:
              secretKeyRef:
                name: te-creds
                key: TEAGENT_ACCOUNT_TOKEN
           - name: TEAGENT_INET
             value: "4"
         resources:
             limits:
               memory: 3584Mi
             requests:
               memory: 2000Mi

