apiVersion: batch/v1
kind: Job
metadata:
  name: loadgen
spec:
  template:
    metadata:
      name: loadgen
    spec:
      containers:
      - name: locust
        image: locustio/locust
        tty: true
        stdin: true
        stdinOnce: true
        env:
        - name: LOCUSTFILE_PATH
          value: /mnt/locustfile.py
        - name: LOCUST_OPTS
          valueFrom:
            configMapKeyRef:
              name: locust-config
              key: locustOpts
        - name: TARGET_URL
          valueFrom:
            configMapKeyRef:
              name: locust-config
              key: targetUrl
        volumeMounts:
        - name: locust-file-vol
          mountPath: /mnt/locustfile.py
          subPath: locustfile.py
      volumes:
      - name: locust-file-vol
        configMap:
          name: locust-file
      restartPolicy: Never
