apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: obi-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
        - name: curl
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for frontend to start..."
              sleep 15
              echo "Starting load generation..."
              while true; do
                curl -s http://frontend:3000/create-order
                sleep 2
              done
