#!/usr/bin/env bash

set -Eeuo pipefail

if [[ "$#" -ne 1 ]]; then
	echo "Usage: down SLUG"
	exit 1
fi

COMMANDS="terraform"

for cmd in $COMMANDS; do
	if ! command -v "$cmd" &> /dev/null; then
		echo "$cmd not found. Please install with your package manager, e.g. brew install $cmd."
		exit 1
	fi
done

SLUG=$1

WORKSPACE=o11y-for-$SLUG
NUKE_PLAN=tfplan-$SLUG-destroy
TFVARS=( -var-file="$SLUG.tfvars" )

terraform workspace select "$WORKSPACE"
terraform plan -destroy "${TFVARS[@]}" -input=false -out="$NUKE_PLAN"
terraform apply -input=false -parallelism=25 "$NUKE_PLAN"
terraform workspace select default
terraform workspace delete "$WORKSPACE"
