#!/usr/bin/env bash

set -Eeuo pipefail

STATUS_LOG=/run/cloud-init/status.json

if [[ "$#" -ne 1 ]]; then
	echo "Usage: up SLUG"
	echo "  SLUG   Short name/tag, e.g. acme. Used to derive project name, aws tags and terraform workspace."
	exit 1
fi

COMMANDS="jq yq terraform pssh"

for cmd in $COMMANDS; do
	if ! command -v "$cmd" &> /dev/null; then
		echo "$cmd not found. Please install with your package manager, e.g. brew install $cmd."
		exit 1
	fi
done

SLUG=$1

WORKSPACE=$SLUG
CREATE_PLAN=tfplan-$SLUG-create
CLOUD_INIT=../../cloud-init/k3s.yaml
TFVARS=( -var-file="$SLUG.tfvars")

terraform workspace select "$WORKSPACE" || terraform workspace new "$WORKSPACE"
# shellcheck disable=SC2086
terraform plan "${TFVARS[@]}" -input=false -out="$CREATE_PLAN"
while :; do
	terraform apply -input=false "$CREATE_PLAN"

	sanity_check_tmp=$(mktemp -d)
	pssh -o "${sanity_check_tmp}" --par 60 -l ubuntu -A --hosts <(terraform output --json ip_addresses|jq -r '.[]') -x "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAuthentication=yes IdentitiesOnly=yes PasswordAuthentication=no ChallengeResponseAuthentication=no CanonicalizeHostname=yes" -- "cat ${STATUS_LOG}"

	ERR_COUNT=$(jq ' .v1 | .[] | values | select(.errors? | length > 0) | .errors[] ' "${sanity_check_tmp}"/* | jq -rs '. | length')

	if [[ $ERR_COUNT -eq 0 ]]; then
		echo "All instances completed cloud-init without errors."
		break;
	else
		echo "Errors found in cloud-init status for some instances."
		jq -r '.v1 | .[] | values | select(.errors? | length > 0) | input_filename' "${sanity_check_tmp}"/* |
			sed -e 's,sanity-check/,,' |
			{ TF_STATE=$(terraform show --json); while read -r IP; do \
				RNAME=$(jq -r ' .values.root_module.resources[] | select (.values.public_ip == "'"$IP"'") | .address' <<< "$TF_STATE")
				echo "Error found in cloud-init status for instance: $RNAME"
				# shellcheck disable=SC2086
				terraform destroy ${TFVARS} -target "'$RNAME'"
			done }
	fi
done
