name: Release new major version

permissions: write-all

on: workflow_dispatch

jobs:
  deploy:
    name: Release new major version
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/deploy
        id: deploy
        with:
          flavour: major
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.deploy.outputs.tag_name }}
          tag_name: v${{ steps.deploy.outputs.tag_name }}
