name: Devbuild

# Controls when the action will run. Triggers manually
on: workflow_dispatch

jobs:
  devbuild:
    name: Build dev version
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/deploy
        with:
          flavour: dev
